# Generated by Django 5.0.4 on 2024-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2000)),
                ('token', models.CharField(max_length=6, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-click_count'],
            },
        ),
    ]
