# Generated by Django 5.0.4 on 2024-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
